[package]
name = "AccountManagerWithActix"
version = "5.0.0"
authors = ["Anest"]
edition = "2018"

[dependencies]
rand = "0.8.3"
rusqlite = "0.24.2"
base64 = "0.13.0"
chrono = "0.4.19"
actix-web = { version = "3", features = ["rustls"] }
serde = "1.0.120"
rustls = "0.18"